### ISSUE TITLE
ECONNRESET (Connection reset by peer)

### ISSUE THREAD

**Issue by benitovc** [paritytrading/philadelphia#70]
Hi, I´s using Philadelphia to conect as initiator to a FIX Gateway Server, but I´m receiving disconnection after receive an important amount of messages; the following is the stack:
    IN:35=X|34=10966|49=DFIXS01|52=20180815-01:02:44.926|56=CFIX10|262=2|268=1|279=2|55=USD/CLP|269=0|270=630.45|271=250000|278=GKJH40|290=1|1023=5|1021=3|1300=39|1301=XBCL|
08-14 20:03:16.110 627-968/com.bvcapps.marketdata A/texto: App recvfrom failed: ECONNRESET (Connection reset by peer)
08-14 20:03:16.140 627-968/com.bvcapps.marketdata W/System.err: java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
        at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:545)
        at libcore.io.IoBridge.recvfrom(IoBridge.java:521)
        at java.nio.SocketChannelImpl.readImpl(SocketChannelImpl.java:327)
        at java.nio.SocketChannelImpl.read(SocketChannelImpl.java:289)
        at com.paritytrading.philadelphia.FIXSession.receive(FIXSession.java:400)
        at com.bvcapps.marketdata.ConexionFIX.receive(ConexionFIX.java:256)
        at com.bvcapps.marketdata.MainActivity$8.run(MainActivity.java:678)
        at java.lang.Thread.run(Thread.java:841)
    Caused by: libcore.io.ErrnoException: recvfrom failed: ECONNRESET (Connection reset by peer)
        at libcore.io.Posix.recvfromBytes(Native Method)
        at libcore.io.Posix.recvfrom(Posix.java:134)
        at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:159)
        at libcore.io.IoBridge.recvfrom(IoBridge.java:518)

The first lie is an output I inserted when a FIX message is received.
When it happend, Server is continue sending messages until 34=11124 and at this point reports connection lost.

**Comment by jvirtanen** [comment]
Are you sending anything from the client side? Are you calling `updateTimestamp()` and `keepAlive()` periodically?

**Comment by benitovc** [comment]
No, I´m not sending any message, I thought philadelphia was sending keepAlive.

**Comment by jvirtanen** [comment]
No, you have to invoke `keepAlive()` periodically yourself.

**Comment by benitovc** [comment]
Ok, I will include a thread to call keepAlive() periodically. Thanks.

**Comment by jvirtanen** [comment]
Great! Remember that [keep-alive and data transmission should either run on the same thread or on different threads with locking](https://github.com/paritytrading/philadelphia/blob/8cf7ee37707d34bf29d166386200b4b0f81bd3af/libraries/core/src/main/java/com/paritytrading/philadelphia/package-info.java#L14).
